### ISSUE TITLE
Add type declarations for TypeScript

### ISSUE THREAD

**Issue by bilo-io** [dimitridumont/clear-cache#2]
Hi @dimitridumont 

This is not a necessarily an issue, but rather a friendly request whether you could add / create `@types/clear-cache`.

I would like to add this repo to one of my projects that is built with TypeScript, and currently I'm seeing this message:

![image](https://user-images.githubusercontent.com/3089012/116865084-40655d00-ac09-11eb-8b0c-a013ba83018f.png)

**Comment by dimitridumont** [comment]
Hello @bilo-io, thank you for using this package

Indeed, currently this package is only in JavaScript. I will add the types for the projects made in TypeScript

**Comment by dimitridumont** [comment]
Resolved by https://github.com/dimitridumont/clear-cache/pull/3
